/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-23 00:38:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class IT2259_005fUpdateCustomer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"IT2259_CustomerInsert.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"event.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\" >\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gabarito:wght@700;800&family=Poppins:wght@600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b3ca95fff7.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Cabin:wght@600&family=Gabarito:wght@700;800&family=Poppins:wght@600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<title>Update Account</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

	
		String id = request.getParameter("id");
		String name = request.getParameter("name");
		String phone = request.getParameter("phone");
		String email = request.getParameter("email");
		String username = request.getParameter("username");
		String password = request.getParameter("password");
	
	
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("        <a href = \"IT2259_HomePage.jsp\"><img src = \"logo.png\" class = \"logo\"></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href = \"IT2259_HomePage.jsp\">Home</li>\r\n");
      out.write("            <li><a href = \"#\">Contact</li>\r\n");
      out.write("            <li><a href = \"IT22592156_About.html\">About</a></li>\r\n");
      out.write("            <i class=\"fa-solid fa-bars fa-lg\" style=\"color: #ffffff;\"></i>\r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("    </header>\r\n");
      out.write("<div class=\"loginn\">\r\n");
      out.write("      <h1 id=\"logtitle\">Update Account</h1><br>\r\n");
      out.write("      <form class=\"loginform\" action=\"update\" method=\"post\" onsubmit=\"return validateForm();\">\r\n");
      out.write("     \r\n");
      out.write("     <i class=\"fa-solid fa-id-card\" style=\"color: #ffffff;\"></i>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Id\" name=\"cusid\" value = \"");
      out.print( id);
      out.write("\" readonly><br><br> \r\n");
      out.write("      \r\n");
      out.write("    <i class=\"fa-solid fa-user\" style=\"color: #ffffff;\"></i>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Name\" name=\"name\"  value = \"");
      out.print( name);
      out.write("\"><br><br>\r\n");
      out.write("    \r\n");
      out.write("    <i class=\"fa-solid fa-phone\" style=\"color: #ffffff;\"></i>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Mobile Number\" name=\"phone\" id=\"phone\" value = \"");
      out.print( phone);
      out.write("\"><br><br>\r\n");
      out.write("    \r\n");
      out.write("    <i class=\"fa-solid fa-envelope\" style=\"color: #ffffff;\"></i>\r\n");
      out.write("    <input type=\"email\" placeholder=\"Email\" name=\"email\" id=\"email\" value = \"");
      out.print( email);
      out.write("\"><br><br>\r\n");
      out.write("   \r\n");
      out.write("    <i class=\"fa-solid fa-check\" style=\"color: #ffffff;\"></i>\r\n");
      out.write("    <input type=\"text\" placeholder=\"User name\" name=\"uid\" value = \"");
      out.print( username);
      out.write("\"><br><br>\r\n");
      out.write("    \r\n");
      out.write("    <i class=\"fa-solid fa-lock\" style=\"color: #ffffff;\"></i>\r\n");
      out.write("    <input type=\"password\" placeholder=\"Password\" name=\"password\" value = \"");
      out.print( password);
      out.write("\"><br><br>\r\n");
      out.write("\r\n");
      out.write("    <input type=\"submit\" id=\"loginformbtn\" value=\"Update\" name=\"submit\">\r\n");
      out.write("</form>\r\n");
      out.write("  </div>\r\n");
      out.write("<script>\r\n");
      out.write("function validateForm() {\r\n");
      out.write("    var phone = document.getElementById(\"phone\").value;\r\n");
      out.write("    var email = document.getElementById(\"email\").value;\r\n");
      out.write("    \r\n");
      out.write("    // Phone number validation\r\n");
      out.write("    if (phone.length < 10 || phone.length >=11 ) {\r\n");
      out.write("        alert(\"Phone number should have 10 digits only.\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Email validation\r\n");
      out.write("    if (email.indexOf(\"@\") === -1 || email.indexOf(\".\") === -1) {\r\n");
      out.write("        alert(\"Please enter a valid email address.\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    return true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
