/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-17 14:08:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class IT22592156_005fhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"IT22592156_HomeCss.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"IT22592156_Event.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gabarito:wght@700;800&family=Poppins:wght@600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Cabin:wght@600&family=Gabarito:wght@700;800&family=Poppins:wght@600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <a href = \"#\"><img src = \"logo.png\" class = \"logo\"></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href = \"IT22592156_home.jsp\">Home</li>\r\n");
      out.write("            <li><a href = \"#\">Contact</li>\r\n");
      out.write("            <li><a href = \"IT22592156_About.jsp\">About</li>\r\n");
      out.write("            <li><button class = \"Login\"><a href = \"#\" id = \"loginbtn\">Login</a></button></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div id=\"slide\">\r\n");
      out.write("            <div class=\"item\" style=\"background-image: url(https://schoolofmusic.ucla.edu/app/uploads/2023/03/Diar_web-1-scaled.jpg);\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"name\">Accostic Concet </div>   \r\n");
      out.write("                    <div class=\"des\"><h2>Saturday, May 20th, 2023</h2>The Acoustic Concert is an enchanting evening of soul-soothing music, featuring talented artists who showcase their acoustic talents. It's an intimate gathering that celebrates the beauty of acoustic soundscapes.</div>\r\n");
      out.write("                    <button class = \"seemore\">See more</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\" style=\"background-image: url(https://www.jonesaroundtheworld.com/wp-content/uploads/2019/09/Bonnaroo-Music-Festival-Best-2020-Festivals.jpg);\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"name\">BOMAROO</div>\r\n");
      out.write("                    <div class=\"des\"><h2> Thursday, August 3rd, 2023, to Sunday, August 6th, 2023</h2>BOMAROO is a vibrant and diverse music and arts festival, offering an immersive experience with top-tier musical acts, mesmerizing art installations, and a sense of community like no other.</div>\r\n");
      out.write("                    <button class = \"seemore\">See more</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\" style=\"background-image: url(https://photo-assets.usopen.org/images/pics/large/f_20230825_USO_Q3_DN1_0669.jpg);\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"name\">Open Mic 2023</div>\r\n");
      out.write("                    <div class=\"des\"><h2>Friday, June 9th, 2023</h2>Open Mic 2023 is an inclusive platform for budding artists, poets, musicians, and comedians to shine. It's a night filled with raw talent, heartfelt performances, and supportive camaraderie.</div>\r\n");
      out.write("                    <button class = \"seemore\">See more</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"buttons\">\r\n");
      out.write("            <button id=\"prev\"><i class=\"fa-solid fa-angle-left\"></i></button>\r\n");
      out.write("            <button id=\"next\"><i class=\"fa-solid fa-angle-right\"></i></button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class = \"upcoming\">\r\n");
      out.write("        <div class = \"upcomingName\"><h1>UPCOMING EVENTS</h1></div>\r\n");
      out.write("        <div class = \"Eventss\" id = \"Eventss1\">\r\n");
      out.write("            <div class = \"event\" id = \"event1\">\r\n");
      out.write("                <div id = \"detailsupEvent\">BAJAWWA</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class = \"event\" id = \"event2\">\r\n");
      out.write("                <div id = \"detailsupEvent\">DREAM MUSIC FEST</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class = \"event\" id = \"event3\">\r\n");
      out.write("                <div id = \"detailsupEvent\">MARYITES</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class = \"Eventss\" id = \"Eventss2\">\r\n");
      out.write("            <div class = \"event\" id = \"event1\">\r\n");
      out.write("                <div id = \"detailsupEvent\">BAJAWWA</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class = \"event\" id = \"event2\">\r\n");
      out.write("                <div id = \"detailsupEvent\">DREAM MUSIC FEST</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class = \"event\" id = \"event3\">\r\n");
      out.write("                <div id = \"detailsupEvent\">MARYITES</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"IT22592156_scriptHome.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
